### PR TITLE
Timing tags

### PR DESCRIPTION
**Pull request by mishanthrop**
Added timing tags ([^t^], [^q^], [^qt^]).
Related issue: https://github.com/baoweb/modx-queeg/issues/4
screenshot_2018-07-10_10-58-23

### CODE REVIEW

**Comment by bartholomej** [comment]
Great work! Thanks. I accepted your PR and also made it configurable in system settings.

**Comment by bartholomej** [comment]
@mishantrop Released at modx store now as v1.3.0: https://modx.com/extras/package/queeg and updated on three of my websites already. Works like a charm.
I am just thinking about the default configuration. Now it is turned ON by default, but since this extension is also using by clients (not only developers)... ...
Any opinion?

**Comment by mishanthrop** [comment]
On the one hand, this package usually installed by developers. This function is usually useful only at the time of development and they always can disable this option after development. Also they will quickly notice this new functions. 

On the other hand... Hm, at this moment I dont see any arguments against turning off this function by default.

**Comment by bartholomej** [comment]
OK we let it turned on by default. Develeopers can always turn it off manually, otherwise they wouldn't have even noticed this feature :)

**Comment by bartholomej** [comment]
@mishantrop We'd like to invite you to be collaborator on this repostiory and looking forward for a new features 😃 🎉 
You don't have to create forks anymore, just create branch in this repository.
But please still use PR before merging to master ;)

**Pull request merged**
